# # # # # # # # # # #
#   Guicciardi.net  #
# # # # # # # # # # #

# Basic
name: "Emanuele Guicciardi"
description: "Senior Developer"

url: "https://guicciardi.net"
author: "Emanuele Guicciardi"

# URL
baseurl: ""
permalink: /:year/:month/:day/:title/

# Markdown
markdown: kramdown

# Google Analytics
google-analytics:
 id: "UA-270658-21"

# Google verification
google-verification:
 id: "AQUR9Im6qs0CPNge5LIUQL5nVBMA8Jlz9BKp5YB8wW0"

# Navigation
nav:
- name: "Home"
  href: "/"
- name: "About"
  href: "/about"
- name: "Skills"
  href: "/skills"
- name: "Notes"
  href: "//github.com/eguicciardi/notes"
  target: "blank"
- name: "Digest"
  href: "//md5.guicciardi.net"
  target: "blank"
- name: "Contact"
  href: "/contact"
  target: "blank"

  # Sass
sass:
  style: compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Plugins
plugins:
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-feed
  - jekyll-gzip
  - jekyll-sitemap

# Collections

collections:
  - experiences
